# Generated by Django 3.1.2 on 2020-10-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.TextField(default='Project'),
            preserve_default=False,
        ),
    ]
